### ISSUE TITLE
[PE-D] Only integer input for all quantity #180

### ISSUE THREAD

**Issue by jinfayap** [AY1920S2-CS2113T-M16-2/tp#228]
It's kind of weird for recipe to have only integer value, might not fit user need.

Labels: `severity.VeryLow` `type.FeatureFlaw`
original: https://github.com/Anqi-nus/ped/issues/8

**Comment by jinfayap** [comment]
Not sure what is this asking.

**Comment by alwayshuizhen** [comment]
This will be closed as the OP has yet to respond to my queries
