### ISSUE TITLE
Syncing fork with upstream

### ISSUE THREAD

**Issue by damithc** [AY1920S2-CS2113T-M16-2/tp#8]
Tutor Ryan alerted me that some of you guys could have misunderstood how to sync your fork with the upstream repo (i.e., the team repo).

* Correct: pull the master branch from upstream repo to your own local clone, and then, push that master branch to your fork
* Incorrect: create PR from upstream to your repo. 

Syncing your copies with the upstream is to be done via your local copy. Don't try to do it directly from one remote repo to another via GitHub PRs.

Use PRs to propose code from your fork to the upstream repo only.

Isabella, FYI.

**Comment by jinfayap** [comment]
Yes, I have also misunderstood the syncing of fork with the upstream repository as well.

If I understood it correctly from what you say, the correct way to pull the upstream repository to the local copy, these are the steps to follow it:

Using of SourceTree 
![upstream_setup1](https://user-images.githubusercontent.com/42379721/75733997-b8987000-5d31-11ea-97a4-80ec01845863.jpeg)
1. Go to repository setting

![upstream_setup2](https://user-images.githubusercontent.com/42379721/75734021-c817b900-5d31-11ea-813a-5f6aadc8dbc0.jpeg)
2. Shows you the remote repository path, add an remote path of the upstream to the setting

![upstream_setup3](https://user-images.githubusercontent.com/42379721/75734068-e382c400-5d31-11ea-914c-415e75c26f48.jpeg)
3. Image of adding the upstream path, and clicking Ok.

![upstream_setup4](https://user-images.githubusercontent.com/42379721/75734234-5b50ee80-5d32-11ea-811e-7cfd041c9c2d.jpeg)
4. Fetch the commits from the upstream repo and check it is correct commits

![upstream_setup5](https://user-images.githubusercontent.com/42379721/75734477-03ff4e00-5d33-11ea-906c-0d950104e6a9.jpeg)
5. Pull the commits from the upstream repository master, this will make local changes in your local repository

6. Push the local copy repository back to your own remote repository

Using of Command Line interface [a rough idea, do check the command for these usage]
1. git remote add upstream https://github.com/AY1920S2-CS2113T-M16-2/tp.git
You can check by "git remote -v"
2. git fetch upstream master
3. git pull upstream master
4. git push origin master

**Comment by damithc** [comment]
That's right @jinfayap 
Thanks for sharing detailed instructions.
